// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBicLnJv0aGYE2CPDpVss8h1_FVfDShv4',
    appId: '1:724753266915:web:1577886bd6d7c712ac6dd6',
    messagingSenderId: '724753266915',
    projectId: 'fruit-hub-ee819',
    authDomain: 'fruit-hub-ee819.firebaseapp.com',
    storageBucket: 'fruit-hub-ee819.firebasestorage.app',
    measurementId: 'G-LRWGXWJ8H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_l-GXT79zGOdBhhRUhSAPLA2whLkMz4Y',
    appId: '1:724753266915:android:ff0f672173f8cd55ac6dd6',
    messagingSenderId: '724753266915',
    projectId: 'fruit-hub-ee819',
    storageBucket: 'fruit-hub-ee819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNcAjB7Q7kS2JoSGH6_foHjY6rKNTLAw',
    appId: '1:724753266915:ios:ba6c7976a3f88609ac6dd6',
    messagingSenderId: '724753266915',
    projectId: 'fruit-hub-ee819',
    storageBucket: 'fruit-hub-ee819.firebasestorage.app',
    iosBundleId: 'com.example.fruitshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNcAjB7Q7kS2JoSGH6_foHjY6rKNTLAw',
    appId: '1:724753266915:ios:ba6c7976a3f88609ac6dd6',
    messagingSenderId: '724753266915',
    projectId: 'fruit-hub-ee819',
    storageBucket: 'fruit-hub-ee819.firebasestorage.app',
    iosBundleId: 'com.example.fruitshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBicLnJv0aGYE2CPDpVss8h1_FVfDShv4',
    appId: '1:724753266915:web:fa1e6948eb1b0269ac6dd6',
    messagingSenderId: '724753266915',
    projectId: 'fruit-hub-ee819',
    authDomain: 'fruit-hub-ee819.firebaseapp.com',
    storageBucket: 'fruit-hub-ee819.firebasestorage.app',
    measurementId: 'G-27ZSYEC8LL',
  );
}
